/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1alpha1WorkflowInputs;
import dev.oam.core.models.V1alpha1WorkflowOutputs;
import dev.oam.core.models.V1alpha1WorkflowSubSteps;
import dev.oam.core.models.V1beta1ApplicationSpecWorkflowMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WorkflowStep defines how to execute a workflow step.
 */
@ApiModel(description = "WorkflowStep defines how to execute a workflow step.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1alpha1WorkflowSteps {
  public static final String SERIALIZED_NAME_DEPENDS_ON = "dependsOn";
  @SerializedName(SERIALIZED_NAME_DEPENDS_ON)
  private List<String> dependsOn = null;

  public static final String SERIALIZED_NAME_IF = "if";
  @SerializedName(SERIALIZED_NAME_IF)
  private String _if;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<V1alpha1WorkflowInputs> inputs = null;

  public static final String SERIALIZED_NAME_META = "meta";
  @SerializedName(SERIALIZED_NAME_META)
  private V1beta1ApplicationSpecWorkflowMeta meta;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private List<V1alpha1WorkflowOutputs> outputs = null;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Object properties;

  public static final String SERIALIZED_NAME_SUB_STEPS = "subSteps";
  @SerializedName(SERIALIZED_NAME_SUB_STEPS)
  private List<V1alpha1WorkflowSubSteps> subSteps = null;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private String timeout;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1alpha1WorkflowSteps dependsOn(List<String> dependsOn) {
    
    this.dependsOn = dependsOn;
    return this;
  }

  public V1alpha1WorkflowSteps addDependsOnItem(String dependsOnItem) {
    if (this.dependsOn == null) {
      this.dependsOn = new ArrayList<>();
    }
    this.dependsOn.add(dependsOnItem);
    return this;
  }

   /**
   * DependsOn is the dependency of the step
   * @return dependsOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "DependsOn is the dependency of the step")

  public List<String> getDependsOn() {
    return dependsOn;
  }


  public void setDependsOn(List<String> dependsOn) {
    this.dependsOn = dependsOn;
  }


  public V1alpha1WorkflowSteps _if(String _if) {
    
    this._if = _if;
    return this;
  }

   /**
   * If is the if condition of the step
   * @return _if
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If is the if condition of the step")

  public String getIf() {
    return _if;
  }


  public void setIf(String _if) {
    this._if = _if;
  }


  public V1alpha1WorkflowSteps inputs(List<V1alpha1WorkflowInputs> inputs) {
    
    this.inputs = inputs;
    return this;
  }

  public V1alpha1WorkflowSteps addInputsItem(V1alpha1WorkflowInputs inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Inputs is the inputs of the step
   * @return inputs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Inputs is the inputs of the step")

  public List<V1alpha1WorkflowInputs> getInputs() {
    return inputs;
  }


  public void setInputs(List<V1alpha1WorkflowInputs> inputs) {
    this.inputs = inputs;
  }


  public V1alpha1WorkflowSteps meta(V1beta1ApplicationSpecWorkflowMeta meta) {
    
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationSpecWorkflowMeta getMeta() {
    return meta;
  }


  public void setMeta(V1beta1ApplicationSpecWorkflowMeta meta) {
    this.meta = meta;
  }


  public V1alpha1WorkflowSteps name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the unique name of the workflow step.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name is the unique name of the workflow step.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha1WorkflowSteps outputs(List<V1alpha1WorkflowOutputs> outputs) {
    
    this.outputs = outputs;
    return this;
  }

  public V1alpha1WorkflowSteps addOutputsItem(V1alpha1WorkflowOutputs outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * Outputs is the outputs of the step
   * @return outputs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Outputs is the outputs of the step")

  public List<V1alpha1WorkflowOutputs> getOutputs() {
    return outputs;
  }


  public void setOutputs(List<V1alpha1WorkflowOutputs> outputs) {
    this.outputs = outputs;
  }


  public V1alpha1WorkflowSteps properties(Object properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Properties is the properties of the step
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Properties is the properties of the step")

  public Object getProperties() {
    return properties;
  }


  public void setProperties(Object properties) {
    this.properties = properties;
  }


  public V1alpha1WorkflowSteps subSteps(List<V1alpha1WorkflowSubSteps> subSteps) {
    
    this.subSteps = subSteps;
    return this;
  }

  public V1alpha1WorkflowSteps addSubStepsItem(V1alpha1WorkflowSubSteps subStepsItem) {
    if (this.subSteps == null) {
      this.subSteps = new ArrayList<>();
    }
    this.subSteps.add(subStepsItem);
    return this;
  }

   /**
   * Get subSteps
   * @return subSteps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1WorkflowSubSteps> getSubSteps() {
    return subSteps;
  }


  public void setSubSteps(List<V1alpha1WorkflowSubSteps> subSteps) {
    this.subSteps = subSteps;
  }


  public V1alpha1WorkflowSteps timeout(String timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Timeout is the timeout of the step
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timeout is the timeout of the step")

  public String getTimeout() {
    return timeout;
  }


  public void setTimeout(String timeout) {
    this.timeout = timeout;
  }


  public V1alpha1WorkflowSteps type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type is the type of the workflow step.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type is the type of the workflow step.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1WorkflowSteps v1alpha1WorkflowSteps = (V1alpha1WorkflowSteps) o;
    return Objects.equals(this.dependsOn, v1alpha1WorkflowSteps.dependsOn) &&
        Objects.equals(this._if, v1alpha1WorkflowSteps._if) &&
        Objects.equals(this.inputs, v1alpha1WorkflowSteps.inputs) &&
        Objects.equals(this.meta, v1alpha1WorkflowSteps.meta) &&
        Objects.equals(this.name, v1alpha1WorkflowSteps.name) &&
        Objects.equals(this.outputs, v1alpha1WorkflowSteps.outputs) &&
        Objects.equals(this.properties, v1alpha1WorkflowSteps.properties) &&
        Objects.equals(this.subSteps, v1alpha1WorkflowSteps.subSteps) &&
        Objects.equals(this.timeout, v1alpha1WorkflowSteps.timeout) &&
        Objects.equals(this.type, v1alpha1WorkflowSteps.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dependsOn, _if, inputs, meta, name, outputs, properties, subSteps, timeout, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1WorkflowSteps {\n");
    sb.append("    dependsOn: ").append(toIndentedString(dependsOn)).append("\n");
    sb.append("    _if: ").append(toIndentedString(_if)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    subSteps: ").append(toIndentedString(subSteps)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

