/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A ChildResourceKind defines a child Kubernetes resource kind with a selector
 */
@ApiModel(description = "A ChildResourceKind defines a child Kubernetes resource kind with a selector")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1WorkloadDefinitionSpecChildResourceKinds {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_SELECTOR = "selector";
  @SerializedName(SERIALIZED_NAME_SELECTOR)
  private Map<String, String> selector = null;


  public V1beta1WorkloadDefinitionSpecChildResourceKinds apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion of the child resource
   * @return apiVersion
  **/
  @ApiModelProperty(required = true, value = "APIVersion of the child resource")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public V1beta1WorkloadDefinitionSpecChildResourceKinds kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Kind of the child resource
   * @return kind
  **/
  @ApiModelProperty(required = true, value = "Kind of the child resource")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public V1beta1WorkloadDefinitionSpecChildResourceKinds selector(Map<String, String> selector) {
    
    this.selector = selector;
    return this;
  }

  public V1beta1WorkloadDefinitionSpecChildResourceKinds putSelectorItem(String key, String selectorItem) {
    if (this.selector == null) {
      this.selector = new HashMap<>();
    }
    this.selector.put(key, selectorItem);
    return this;
  }

   /**
   * Selector to select the child resources that the workload wants to expose to traits
   * @return selector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Selector to select the child resources that the workload wants to expose to traits")

  public Map<String, String> getSelector() {
    return selector;
  }


  public void setSelector(Map<String, String> selector) {
    this.selector = selector;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkloadDefinitionSpecChildResourceKinds v1beta1WorkloadDefinitionSpecChildResourceKinds = (V1beta1WorkloadDefinitionSpecChildResourceKinds) o;
    return Objects.equals(this.apiVersion, v1beta1WorkloadDefinitionSpecChildResourceKinds.apiVersion) &&
        Objects.equals(this.kind, v1beta1WorkloadDefinitionSpecChildResourceKinds.kind) &&
        Objects.equals(this.selector, v1beta1WorkloadDefinitionSpecChildResourceKinds.selector);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, selector);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkloadDefinitionSpecChildResourceKinds {\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

