/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationSpecWorkflowMode;
import dev.oam.core.models.V1beta1ApplicationSpecWorkflowSteps;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Workflow defines how to customize the control logic. If workflow is specified, Vela won&#39;t apply any resource, but provide rendered output in AppRevision. Workflow steps are executed in array order, and each step: - will have a context in annotation. - should mark \&quot;finish\&quot; phase in status.conditions.
 */
@ApiModel(description = "Workflow defines how to customize the control logic. If workflow is specified, Vela won't apply any resource, but provide rendered output in AppRevision. Workflow steps are executed in array order, and each step: - will have a context in annotation. - should mark \"finish\" phase in status.conditions.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationSpecWorkflow {
  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private V1beta1ApplicationSpecWorkflowMode mode;

  public static final String SERIALIZED_NAME_REF = "ref";
  @SerializedName(SERIALIZED_NAME_REF)
  private String ref;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<V1beta1ApplicationSpecWorkflowSteps> steps = null;


  public V1beta1ApplicationSpecWorkflow mode(V1beta1ApplicationSpecWorkflowMode mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationSpecWorkflowMode getMode() {
    return mode;
  }


  public void setMode(V1beta1ApplicationSpecWorkflowMode mode) {
    this.mode = mode;
  }


  public V1beta1ApplicationSpecWorkflow ref(String ref) {
    
    this.ref = ref;
    return this;
  }

   /**
   * Get ref
   * @return ref
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRef() {
    return ref;
  }


  public void setRef(String ref) {
    this.ref = ref;
  }


  public V1beta1ApplicationSpecWorkflow steps(List<V1beta1ApplicationSpecWorkflowSteps> steps) {
    
    this.steps = steps;
    return this;
  }

  public V1beta1ApplicationSpecWorkflow addStepsItem(V1beta1ApplicationSpecWorkflowSteps stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1ApplicationSpecWorkflowSteps> getSteps() {
    return steps;
  }


  public void setSteps(List<V1beta1ApplicationSpecWorkflowSteps> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationSpecWorkflow v1beta1ApplicationSpecWorkflow = (V1beta1ApplicationSpecWorkflow) o;
    return Objects.equals(this.mode, v1beta1ApplicationSpecWorkflow.mode) &&
        Objects.equals(this.ref, v1beta1ApplicationSpecWorkflow.ref) &&
        Objects.equals(this.steps, v1beta1ApplicationSpecWorkflow.steps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mode, ref, steps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationSpecWorkflow {\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

