/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationStatusComponents;
import dev.oam.core.models.V1beta1ApplicationStatusWorkflowSteps;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Workflow record the status of workflow
 */
@ApiModel(description = "Workflow record the status of workflow")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationStatusWorkflow {
  public static final String SERIALIZED_NAME_APP_REVISION = "appRevision";
  @SerializedName(SERIALIZED_NAME_APP_REVISION)
  private String appRevision;

  public static final String SERIALIZED_NAME_CONTEXT_BACKEND = "contextBackend";
  @SerializedName(SERIALIZED_NAME_CONTEXT_BACKEND)
  private V1beta1ApplicationStatusComponents contextBackend;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private Object endTime;

  public static final String SERIALIZED_NAME_FINISHED = "finished";
  @SerializedName(SERIALIZED_NAME_FINISHED)
  private Boolean finished;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private String mode;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private OffsetDateTime startTime;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<V1beta1ApplicationStatusWorkflowSteps> steps = null;

  public static final String SERIALIZED_NAME_SUSPEND = "suspend";
  @SerializedName(SERIALIZED_NAME_SUSPEND)
  private Boolean suspend;

  public static final String SERIALIZED_NAME_SUSPEND_STATE = "suspendState";
  @SerializedName(SERIALIZED_NAME_SUSPEND_STATE)
  private String suspendState;

  public static final String SERIALIZED_NAME_TERMINATED = "terminated";
  @SerializedName(SERIALIZED_NAME_TERMINATED)
  private Boolean terminated;


  public V1beta1ApplicationStatusWorkflow appRevision(String appRevision) {
    
    this.appRevision = appRevision;
    return this;
  }

   /**
   * Get appRevision
   * @return appRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAppRevision() {
    return appRevision;
  }


  public void setAppRevision(String appRevision) {
    this.appRevision = appRevision;
  }


  public V1beta1ApplicationStatusWorkflow contextBackend(V1beta1ApplicationStatusComponents contextBackend) {
    
    this.contextBackend = contextBackend;
    return this;
  }

   /**
   * Get contextBackend
   * @return contextBackend
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationStatusComponents getContextBackend() {
    return contextBackend;
  }


  public void setContextBackend(V1beta1ApplicationStatusComponents contextBackend) {
    this.contextBackend = contextBackend;
  }


  public V1beta1ApplicationStatusWorkflow endTime(Object endTime) {
    
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getEndTime() {
    return endTime;
  }


  public void setEndTime(Object endTime) {
    this.endTime = endTime;
  }


  public V1beta1ApplicationStatusWorkflow finished(Boolean finished) {
    
    this.finished = finished;
    return this;
  }

   /**
   * Get finished
   * @return finished
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getFinished() {
    return finished;
  }


  public void setFinished(Boolean finished) {
    this.finished = finished;
  }


  public V1beta1ApplicationStatusWorkflow message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public V1beta1ApplicationStatusWorkflow mode(String mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(required = true, value = "")

  public String getMode() {
    return mode;
  }


  public void setMode(String mode) {
    this.mode = mode;
  }


  public V1beta1ApplicationStatusWorkflow startTime(OffsetDateTime startTime) {
    
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getStartTime() {
    return startTime;
  }


  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }


  public V1beta1ApplicationStatusWorkflow status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * WorkflowRunPhase is a label for the condition of a WorkflowRun at the current time
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "WorkflowRunPhase is a label for the condition of a WorkflowRun at the current time")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public V1beta1ApplicationStatusWorkflow steps(List<V1beta1ApplicationStatusWorkflowSteps> steps) {
    
    this.steps = steps;
    return this;
  }

  public V1beta1ApplicationStatusWorkflow addStepsItem(V1beta1ApplicationStatusWorkflowSteps stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1ApplicationStatusWorkflowSteps> getSteps() {
    return steps;
  }


  public void setSteps(List<V1beta1ApplicationStatusWorkflowSteps> steps) {
    this.steps = steps;
  }


  public V1beta1ApplicationStatusWorkflow suspend(Boolean suspend) {
    
    this.suspend = suspend;
    return this;
  }

   /**
   * Get suspend
   * @return suspend
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getSuspend() {
    return suspend;
  }


  public void setSuspend(Boolean suspend) {
    this.suspend = suspend;
  }


  public V1beta1ApplicationStatusWorkflow suspendState(String suspendState) {
    
    this.suspendState = suspendState;
    return this;
  }

   /**
   * Get suspendState
   * @return suspendState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSuspendState() {
    return suspendState;
  }


  public void setSuspendState(String suspendState) {
    this.suspendState = suspendState;
  }


  public V1beta1ApplicationStatusWorkflow terminated(Boolean terminated) {
    
    this.terminated = terminated;
    return this;
  }

   /**
   * Get terminated
   * @return terminated
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getTerminated() {
    return terminated;
  }


  public void setTerminated(Boolean terminated) {
    this.terminated = terminated;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationStatusWorkflow v1beta1ApplicationStatusWorkflow = (V1beta1ApplicationStatusWorkflow) o;
    return Objects.equals(this.appRevision, v1beta1ApplicationStatusWorkflow.appRevision) &&
        Objects.equals(this.contextBackend, v1beta1ApplicationStatusWorkflow.contextBackend) &&
        Objects.equals(this.endTime, v1beta1ApplicationStatusWorkflow.endTime) &&
        Objects.equals(this.finished, v1beta1ApplicationStatusWorkflow.finished) &&
        Objects.equals(this.message, v1beta1ApplicationStatusWorkflow.message) &&
        Objects.equals(this.mode, v1beta1ApplicationStatusWorkflow.mode) &&
        Objects.equals(this.startTime, v1beta1ApplicationStatusWorkflow.startTime) &&
        Objects.equals(this.status, v1beta1ApplicationStatusWorkflow.status) &&
        Objects.equals(this.steps, v1beta1ApplicationStatusWorkflow.steps) &&
        Objects.equals(this.suspend, v1beta1ApplicationStatusWorkflow.suspend) &&
        Objects.equals(this.suspendState, v1beta1ApplicationStatusWorkflow.suspendState) &&
        Objects.equals(this.terminated, v1beta1ApplicationStatusWorkflow.terminated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appRevision, contextBackend, endTime, finished, message, mode, startTime, status, steps, suspend, suspendState, terminated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationStatusWorkflow {\n");
    sb.append("    appRevision: ").append(toIndentedString(appRevision)).append("\n");
    sb.append("    contextBackend: ").append(toIndentedString(contextBackend)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    finished: ").append(toIndentedString(finished)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    suspend: ").append(toIndentedString(suspend)).append("\n");
    sb.append("    suspendState: ").append(toIndentedString(suspendState)).append("\n");
    sb.append("    terminated: ").append(toIndentedString(terminated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

