/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LatestRevision of the component definition
 */
@ApiModel(description = "LatestRevision of the component definition")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1WorkflowStepDefinitionStatusLatestRevision {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_REVISION = "revision";
  @SerializedName(SERIALIZED_NAME_REVISION)
  private Long revision;

  public static final String SERIALIZED_NAME_REVISION_HASH = "revisionHash";
  @SerializedName(SERIALIZED_NAME_REVISION_HASH)
  private String revisionHash;


  public V1beta1WorkflowStepDefinitionStatusLatestRevision name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1beta1WorkflowStepDefinitionStatusLatestRevision revision(Long revision) {
    
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getRevision() {
    return revision;
  }


  public void setRevision(Long revision) {
    this.revision = revision;
  }


  public V1beta1WorkflowStepDefinitionStatusLatestRevision revisionHash(String revisionHash) {
    
    this.revisionHash = revisionHash;
    return this;
  }

   /**
   * RevisionHash record the hash value of the spec of ApplicationRevision object.
   * @return revisionHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RevisionHash record the hash value of the spec of ApplicationRevision object.")

  public String getRevisionHash() {
    return revisionHash;
  }


  public void setRevisionHash(String revisionHash) {
    this.revisionHash = revisionHash;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkflowStepDefinitionStatusLatestRevision v1beta1WorkflowStepDefinitionStatusLatestRevision = (V1beta1WorkflowStepDefinitionStatusLatestRevision) o;
    return Objects.equals(this.name, v1beta1WorkflowStepDefinitionStatusLatestRevision.name) &&
        Objects.equals(this.revision, v1beta1WorkflowStepDefinitionStatusLatestRevision.revision) &&
        Objects.equals(this.revisionHash, v1beta1WorkflowStepDefinitionStatusLatestRevision.revisionHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, revision, revisionHash);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkflowStepDefinitionStatusLatestRevision {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    revisionHash: ").append(toIndentedString(revisionHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

