/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1WorkflowStepDefinitionSpecSchematicCue;
import dev.oam.core.models.V1beta1WorkflowStepDefinitionSpecSchematicTerraform;
import dev.oam.core.models.V1beta1WorkloadDefinitionSpecSchematicHelm;
import dev.oam.core.models.V1beta1WorkloadDefinitionSpecSchematicKube;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Schematic defines the data format and template of the encapsulation of the workload
 */
@ApiModel(description = "Schematic defines the data format and template of the encapsulation of the workload")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1WorkloadDefinitionSpecSchematic {
  public static final String SERIALIZED_NAME_CUE = "cue";
  @SerializedName(SERIALIZED_NAME_CUE)
  private V1beta1WorkflowStepDefinitionSpecSchematicCue cue;

  public static final String SERIALIZED_NAME_HELM = "helm";
  @SerializedName(SERIALIZED_NAME_HELM)
  private V1beta1WorkloadDefinitionSpecSchematicHelm helm;

  public static final String SERIALIZED_NAME_KUBE = "kube";
  @SerializedName(SERIALIZED_NAME_KUBE)
  private V1beta1WorkloadDefinitionSpecSchematicKube kube;

  public static final String SERIALIZED_NAME_TERRAFORM = "terraform";
  @SerializedName(SERIALIZED_NAME_TERRAFORM)
  private V1beta1WorkflowStepDefinitionSpecSchematicTerraform terraform;


  public V1beta1WorkloadDefinitionSpecSchematic cue(V1beta1WorkflowStepDefinitionSpecSchematicCue cue) {
    
    this.cue = cue;
    return this;
  }

   /**
   * Get cue
   * @return cue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkflowStepDefinitionSpecSchematicCue getCue() {
    return cue;
  }


  public void setCue(V1beta1WorkflowStepDefinitionSpecSchematicCue cue) {
    this.cue = cue;
  }


  public V1beta1WorkloadDefinitionSpecSchematic helm(V1beta1WorkloadDefinitionSpecSchematicHelm helm) {
    
    this.helm = helm;
    return this;
  }

   /**
   * Get helm
   * @return helm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkloadDefinitionSpecSchematicHelm getHelm() {
    return helm;
  }


  public void setHelm(V1beta1WorkloadDefinitionSpecSchematicHelm helm) {
    this.helm = helm;
  }


  public V1beta1WorkloadDefinitionSpecSchematic kube(V1beta1WorkloadDefinitionSpecSchematicKube kube) {
    
    this.kube = kube;
    return this;
  }

   /**
   * Get kube
   * @return kube
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkloadDefinitionSpecSchematicKube getKube() {
    return kube;
  }


  public void setKube(V1beta1WorkloadDefinitionSpecSchematicKube kube) {
    this.kube = kube;
  }


  public V1beta1WorkloadDefinitionSpecSchematic terraform(V1beta1WorkflowStepDefinitionSpecSchematicTerraform terraform) {
    
    this.terraform = terraform;
    return this;
  }

   /**
   * Get terraform
   * @return terraform
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkflowStepDefinitionSpecSchematicTerraform getTerraform() {
    return terraform;
  }


  public void setTerraform(V1beta1WorkflowStepDefinitionSpecSchematicTerraform terraform) {
    this.terraform = terraform;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkloadDefinitionSpecSchematic v1beta1WorkloadDefinitionSpecSchematic = (V1beta1WorkloadDefinitionSpecSchematic) o;
    return Objects.equals(this.cue, v1beta1WorkloadDefinitionSpecSchematic.cue) &&
        Objects.equals(this.helm, v1beta1WorkloadDefinitionSpecSchematic.helm) &&
        Objects.equals(this.kube, v1beta1WorkloadDefinitionSpecSchematic.kube) &&
        Objects.equals(this.terraform, v1beta1WorkloadDefinitionSpecSchematic.terraform);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cue, helm, kube, terraform);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkloadDefinitionSpecSchematic {\n");
    sb.append("    cue: ").append(toIndentedString(cue)).append("\n");
    sb.append("    helm: ").append(toIndentedString(helm)).append("\n");
    sb.append("    kube: ").append(toIndentedString(kube)).append("\n");
    sb.append("    terraform: ").append(toIndentedString(terraform)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

