/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * A Condition that may apply to a resource.
 */
@ApiModel(description = "A Condition that may apply to a resource.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1WorkflowStepDefinitionStatusConditions {
  public static final String SERIALIZED_NAME_LAST_TRANSITION_TIME = "lastTransitionTime";
  @SerializedName(SERIALIZED_NAME_LAST_TRANSITION_TIME)
  private OffsetDateTime lastTransitionTime;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1beta1WorkflowStepDefinitionStatusConditions lastTransitionTime(OffsetDateTime lastTransitionTime) {
    
    this.lastTransitionTime = lastTransitionTime;
    return this;
  }

   /**
   * LastTransitionTime is the last time this condition transitioned from one status to another.
   * @return lastTransitionTime
  **/
  @ApiModelProperty(required = true, value = "LastTransitionTime is the last time this condition transitioned from one status to another.")

  public OffsetDateTime getLastTransitionTime() {
    return lastTransitionTime;
  }


  public void setLastTransitionTime(OffsetDateTime lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
  }


  public V1beta1WorkflowStepDefinitionStatusConditions message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * A Message containing details about this condition&#39;s last transition from one status to another, if any.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A Message containing details about this condition's last transition from one status to another, if any.")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public V1beta1WorkflowStepDefinitionStatusConditions reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * A Reason for this condition&#39;s last transition from one status to another.
   * @return reason
  **/
  @ApiModelProperty(required = true, value = "A Reason for this condition's last transition from one status to another.")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public V1beta1WorkflowStepDefinitionStatusConditions status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of this condition; is it currently True, False, or Unknown?
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of this condition; is it currently True, False, or Unknown?")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public V1beta1WorkflowStepDefinitionStatusConditions type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of this condition. At most one of each condition type may apply to a resource at any point in time.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of this condition. At most one of each condition type may apply to a resource at any point in time.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkflowStepDefinitionStatusConditions v1beta1WorkflowStepDefinitionStatusConditions = (V1beta1WorkflowStepDefinitionStatusConditions) o;
    return Objects.equals(this.lastTransitionTime, v1beta1WorkflowStepDefinitionStatusConditions.lastTransitionTime) &&
        Objects.equals(this.message, v1beta1WorkflowStepDefinitionStatusConditions.message) &&
        Objects.equals(this.reason, v1beta1WorkflowStepDefinitionStatusConditions.reason) &&
        Objects.equals(this.status, v1beta1WorkflowStepDefinitionStatusConditions.status) &&
        Objects.equals(this.type, v1beta1WorkflowStepDefinitionStatusConditions.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastTransitionTime, message, reason, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkflowStepDefinitionStatusConditions {\n");
    sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

