/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ResourceTrackerSpecCompression;
import dev.oam.core.models.V1beta1ResourceTrackerSpecManagedResources;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ResourceTrackerSpec define the spec of resourceTracker
 */
@ApiModel(description = "ResourceTrackerSpec define the spec of resourceTracker")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ResourceTrackerSpec {
  public static final String SERIALIZED_NAME_APPLICATION_GENERATION = "applicationGeneration";
  @SerializedName(SERIALIZED_NAME_APPLICATION_GENERATION)
  private Long applicationGeneration;

  public static final String SERIALIZED_NAME_COMPRESSION = "compression";
  @SerializedName(SERIALIZED_NAME_COMPRESSION)
  private V1beta1ResourceTrackerSpecCompression compression;

  public static final String SERIALIZED_NAME_MANAGED_RESOURCES = "managedResources";
  @SerializedName(SERIALIZED_NAME_MANAGED_RESOURCES)
  private List<V1beta1ResourceTrackerSpecManagedResources> managedResources = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1beta1ResourceTrackerSpec applicationGeneration(Long applicationGeneration) {
    
    this.applicationGeneration = applicationGeneration;
    return this;
  }

   /**
   * Get applicationGeneration
   * @return applicationGeneration
  **/
  @ApiModelProperty(required = true, value = "")

  public Long getApplicationGeneration() {
    return applicationGeneration;
  }


  public void setApplicationGeneration(Long applicationGeneration) {
    this.applicationGeneration = applicationGeneration;
  }


  public V1beta1ResourceTrackerSpec compression(V1beta1ResourceTrackerSpecCompression compression) {
    
    this.compression = compression;
    return this;
  }

   /**
   * Get compression
   * @return compression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ResourceTrackerSpecCompression getCompression() {
    return compression;
  }


  public void setCompression(V1beta1ResourceTrackerSpecCompression compression) {
    this.compression = compression;
  }


  public V1beta1ResourceTrackerSpec managedResources(List<V1beta1ResourceTrackerSpecManagedResources> managedResources) {
    
    this.managedResources = managedResources;
    return this;
  }

  public V1beta1ResourceTrackerSpec addManagedResourcesItem(V1beta1ResourceTrackerSpecManagedResources managedResourcesItem) {
    if (this.managedResources == null) {
      this.managedResources = new ArrayList<>();
    }
    this.managedResources.add(managedResourcesItem);
    return this;
  }

   /**
   * Get managedResources
   * @return managedResources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1ResourceTrackerSpecManagedResources> getManagedResources() {
    return managedResources;
  }


  public void setManagedResources(List<V1beta1ResourceTrackerSpecManagedResources> managedResources) {
    this.managedResources = managedResources;
  }


  public V1beta1ResourceTrackerSpec type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * ResourceTrackerType defines the type of resourceTracker
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ResourceTrackerType defines the type of resourceTracker")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ResourceTrackerSpec v1beta1ResourceTrackerSpec = (V1beta1ResourceTrackerSpec) o;
    return Objects.equals(this.applicationGeneration, v1beta1ResourceTrackerSpec.applicationGeneration) &&
        Objects.equals(this.compression, v1beta1ResourceTrackerSpec.compression) &&
        Objects.equals(this.managedResources, v1beta1ResourceTrackerSpec.managedResources) &&
        Objects.equals(this.type, v1beta1ResourceTrackerSpec.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationGeneration, compression, managedResources, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ResourceTrackerSpec {\n");
    sb.append("    applicationGeneration: ").append(toIndentedString(applicationGeneration)).append("\n");
    sb.append("    compression: ").append(toIndentedString(compression)).append("\n");
    sb.append("    managedResources: ").append(toIndentedString(managedResources)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

