/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecApplicationMetadata;
import dev.oam.core.models.V1beta1ApplicationSpecWorkflowMode;
import dev.oam.core.models.V1beta1ApplicationSpecWorkflowSteps;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Workflow records the external workflow
 */
@ApiModel(description = "Workflow records the external workflow")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationRevisionSpecWorkflow {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1beta1ApplicationRevisionSpecApplicationMetadata metadata;

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  private V1beta1ApplicationSpecWorkflowMode mode;

  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private List<V1beta1ApplicationSpecWorkflowSteps> steps = null;


  public V1beta1ApplicationRevisionSpecWorkflow apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public V1beta1ApplicationRevisionSpecWorkflow kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public V1beta1ApplicationRevisionSpecWorkflow metadata(V1beta1ApplicationRevisionSpecApplicationMetadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationRevisionSpecApplicationMetadata getMetadata() {
    return metadata;
  }


  public void setMetadata(V1beta1ApplicationRevisionSpecApplicationMetadata metadata) {
    this.metadata = metadata;
  }


  public V1beta1ApplicationRevisionSpecWorkflow mode(V1beta1ApplicationSpecWorkflowMode mode) {
    
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationSpecWorkflowMode getMode() {
    return mode;
  }


  public void setMode(V1beta1ApplicationSpecWorkflowMode mode) {
    this.mode = mode;
  }


  public V1beta1ApplicationRevisionSpecWorkflow steps(List<V1beta1ApplicationSpecWorkflowSteps> steps) {
    
    this.steps = steps;
    return this;
  }

  public V1beta1ApplicationRevisionSpecWorkflow addStepsItem(V1beta1ApplicationSpecWorkflowSteps stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1ApplicationSpecWorkflowSteps> getSteps() {
    return steps;
  }


  public void setSteps(List<V1beta1ApplicationSpecWorkflowSteps> steps) {
    this.steps = steps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationRevisionSpecWorkflow v1beta1ApplicationRevisionSpecWorkflow = (V1beta1ApplicationRevisionSpecWorkflow) o;
    return Objects.equals(this.apiVersion, v1beta1ApplicationRevisionSpecWorkflow.apiVersion) &&
        Objects.equals(this.kind, v1beta1ApplicationRevisionSpecWorkflow.kind) &&
        Objects.equals(this.metadata, v1beta1ApplicationRevisionSpecWorkflow.metadata) &&
        Objects.equals(this.mode, v1beta1ApplicationRevisionSpecWorkflow.mode) &&
        Objects.equals(this.steps, v1beta1ApplicationRevisionSpecWorkflow.steps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, mode, steps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationRevisionSpecWorkflow {\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

