/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Status defines the custom health policy and status message for trait
 */
@ApiModel(description = "Status defines the custom health policy and status message for trait")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1TraitDefinitionSpecStatus {
  public static final String SERIALIZED_NAME_CUSTOM_STATUS = "customStatus";
  @SerializedName(SERIALIZED_NAME_CUSTOM_STATUS)
  private String customStatus;

  public static final String SERIALIZED_NAME_HEALTH_POLICY = "healthPolicy";
  @SerializedName(SERIALIZED_NAME_HEALTH_POLICY)
  private String healthPolicy;


  public V1beta1TraitDefinitionSpecStatus customStatus(String customStatus) {
    
    this.customStatus = customStatus;
    return this;
  }

   /**
   * CustomStatus defines the custom status message that could display to user
   * @return customStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CustomStatus defines the custom status message that could display to user")

  public String getCustomStatus() {
    return customStatus;
  }


  public void setCustomStatus(String customStatus) {
    this.customStatus = customStatus;
  }


  public V1beta1TraitDefinitionSpecStatus healthPolicy(String healthPolicy) {
    
    this.healthPolicy = healthPolicy;
    return this;
  }

   /**
   * HealthPolicy defines the health check policy for the abstraction
   * @return healthPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "HealthPolicy defines the health check policy for the abstraction")

  public String getHealthPolicy() {
    return healthPolicy;
  }


  public void setHealthPolicy(String healthPolicy) {
    this.healthPolicy = healthPolicy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TraitDefinitionSpecStatus v1beta1TraitDefinitionSpecStatus = (V1beta1TraitDefinitionSpecStatus) o;
    return Objects.equals(this.customStatus, v1beta1TraitDefinitionSpecStatus.customStatus) &&
        Objects.equals(this.healthPolicy, v1beta1TraitDefinitionSpecStatus.healthPolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customStatus, healthPolicy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TraitDefinitionSpecStatus {\n");
    sb.append("    customStatus: ").append(toIndentedString(customStatus)).append("\n");
    sb.append("    healthPolicy: ").append(toIndentedString(healthPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

