/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ComponentDefinitionSpecSchematic;
import dev.oam.core.models.V1beta1WorkloadDefinitionSpecChildResourceKinds;
import dev.oam.core.models.V1beta1WorkloadDefinitionSpecDefinitionRef;
import dev.oam.core.models.V1beta1WorkloadDefinitionSpecStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A WorkloadDefinitionSpec defines the desired state of a WorkloadDefinition.
 */
@ApiModel(description = "A WorkloadDefinitionSpec defines the desired state of a WorkloadDefinition.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationRevisionSpecSpec {
  public static final String SERIALIZED_NAME_CHILD_RESOURCE_KINDS = "childResourceKinds";
  @SerializedName(SERIALIZED_NAME_CHILD_RESOURCE_KINDS)
  private List<V1beta1WorkloadDefinitionSpecChildResourceKinds> childResourceKinds = null;

  public static final String SERIALIZED_NAME_DEFINITION_REF = "definitionRef";
  @SerializedName(SERIALIZED_NAME_DEFINITION_REF)
  private V1beta1WorkloadDefinitionSpecDefinitionRef definitionRef;

  public static final String SERIALIZED_NAME_EXTENSION = "extension";
  @SerializedName(SERIALIZED_NAME_EXTENSION)
  private Object extension;

  public static final String SERIALIZED_NAME_POD_SPEC_PATH = "podSpecPath";
  @SerializedName(SERIALIZED_NAME_POD_SPEC_PATH)
  private String podSpecPath;

  public static final String SERIALIZED_NAME_REVISION_LABEL = "revisionLabel";
  @SerializedName(SERIALIZED_NAME_REVISION_LABEL)
  private String revisionLabel;

  public static final String SERIALIZED_NAME_SCHEMATIC = "schematic";
  @SerializedName(SERIALIZED_NAME_SCHEMATIC)
  private V1beta1ComponentDefinitionSpecSchematic schematic;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private V1beta1WorkloadDefinitionSpecStatus status;


  public V1beta1ApplicationRevisionSpecSpec childResourceKinds(List<V1beta1WorkloadDefinitionSpecChildResourceKinds> childResourceKinds) {
    
    this.childResourceKinds = childResourceKinds;
    return this;
  }

  public V1beta1ApplicationRevisionSpecSpec addChildResourceKindsItem(V1beta1WorkloadDefinitionSpecChildResourceKinds childResourceKindsItem) {
    if (this.childResourceKinds == null) {
      this.childResourceKinds = new ArrayList<>();
    }
    this.childResourceKinds.add(childResourceKindsItem);
    return this;
  }

   /**
   * ChildResourceKinds are the list of GVK of the child resources this workload generates
   * @return childResourceKinds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ChildResourceKinds are the list of GVK of the child resources this workload generates")

  public List<V1beta1WorkloadDefinitionSpecChildResourceKinds> getChildResourceKinds() {
    return childResourceKinds;
  }


  public void setChildResourceKinds(List<V1beta1WorkloadDefinitionSpecChildResourceKinds> childResourceKinds) {
    this.childResourceKinds = childResourceKinds;
  }


  public V1beta1ApplicationRevisionSpecSpec definitionRef(V1beta1WorkloadDefinitionSpecDefinitionRef definitionRef) {
    
    this.definitionRef = definitionRef;
    return this;
  }

   /**
   * Get definitionRef
   * @return definitionRef
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1WorkloadDefinitionSpecDefinitionRef getDefinitionRef() {
    return definitionRef;
  }


  public void setDefinitionRef(V1beta1WorkloadDefinitionSpecDefinitionRef definitionRef) {
    this.definitionRef = definitionRef;
  }


  public V1beta1ApplicationRevisionSpecSpec extension(Object extension) {
    
    this.extension = extension;
    return this;
  }

   /**
   * Extension is used for extension needs by OAM platform builders
   * @return extension
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Extension is used for extension needs by OAM platform builders")

  public Object getExtension() {
    return extension;
  }


  public void setExtension(Object extension) {
    this.extension = extension;
  }


  public V1beta1ApplicationRevisionSpecSpec podSpecPath(String podSpecPath) {
    
    this.podSpecPath = podSpecPath;
    return this;
  }

   /**
   * PodSpecPath indicates where/if this workload has K8s podSpec field if one workload has podSpec, trait can do lot&#39;s of assumption such as port, env, volume fields.
   * @return podSpecPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PodSpecPath indicates where/if this workload has K8s podSpec field if one workload has podSpec, trait can do lot's of assumption such as port, env, volume fields.")

  public String getPodSpecPath() {
    return podSpecPath;
  }


  public void setPodSpecPath(String podSpecPath) {
    this.podSpecPath = podSpecPath;
  }


  public V1beta1ApplicationRevisionSpecSpec revisionLabel(String revisionLabel) {
    
    this.revisionLabel = revisionLabel;
    return this;
  }

   /**
   * RevisionLabel indicates which label for underlying resources(e.g. pods) of this workload can be used by trait to create resource selectors(e.g. label selector for pods).
   * @return revisionLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "RevisionLabel indicates which label for underlying resources(e.g. pods) of this workload can be used by trait to create resource selectors(e.g. label selector for pods).")

  public String getRevisionLabel() {
    return revisionLabel;
  }


  public void setRevisionLabel(String revisionLabel) {
    this.revisionLabel = revisionLabel;
  }


  public V1beta1ApplicationRevisionSpecSpec schematic(V1beta1ComponentDefinitionSpecSchematic schematic) {
    
    this.schematic = schematic;
    return this;
  }

   /**
   * Get schematic
   * @return schematic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ComponentDefinitionSpecSchematic getSchematic() {
    return schematic;
  }


  public void setSchematic(V1beta1ComponentDefinitionSpecSchematic schematic) {
    this.schematic = schematic;
  }


  public V1beta1ApplicationRevisionSpecSpec status(V1beta1WorkloadDefinitionSpecStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkloadDefinitionSpecStatus getStatus() {
    return status;
  }


  public void setStatus(V1beta1WorkloadDefinitionSpecStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationRevisionSpecSpec v1beta1ApplicationRevisionSpecSpec = (V1beta1ApplicationRevisionSpecSpec) o;
    return Objects.equals(this.childResourceKinds, v1beta1ApplicationRevisionSpecSpec.childResourceKinds) &&
        Objects.equals(this.definitionRef, v1beta1ApplicationRevisionSpecSpec.definitionRef) &&
        Objects.equals(this.extension, v1beta1ApplicationRevisionSpecSpec.extension) &&
        Objects.equals(this.podSpecPath, v1beta1ApplicationRevisionSpecSpec.podSpecPath) &&
        Objects.equals(this.revisionLabel, v1beta1ApplicationRevisionSpecSpec.revisionLabel) &&
        Objects.equals(this.schematic, v1beta1ApplicationRevisionSpecSpec.schematic) &&
        Objects.equals(this.status, v1beta1ApplicationRevisionSpecSpec.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(childResourceKinds, definitionRef, extension, podSpecPath, revisionLabel, schematic, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationRevisionSpecSpec {\n");
    sb.append("    childResourceKinds: ").append(toIndentedString(childResourceKinds)).append("\n");
    sb.append("    definitionRef: ").append(toIndentedString(definitionRef)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    podSpecPath: ").append(toIndentedString(podSpecPath)).append("\n");
    sb.append("    revisionLabel: ").append(toIndentedString(revisionLabel)).append("\n");
    sb.append("    schematic: ").append(toIndentedString(schematic)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

