/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1PolicyDefinitionSpecSchematic;
import dev.oam.core.models.V1beta1WorkflowStepDefinitionSpecDefinitionRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PolicyDefinitionSpec defines the desired state of PolicyDefinition
 */
@ApiModel(description = "PolicyDefinitionSpec defines the desired state of PolicyDefinition")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1PolicyDefinitionSpec {
  public static final String SERIALIZED_NAME_DEFINITION_REF = "definitionRef";
  @SerializedName(SERIALIZED_NAME_DEFINITION_REF)
  private V1beta1WorkflowStepDefinitionSpecDefinitionRef definitionRef;

  public static final String SERIALIZED_NAME_MANAGE_HEALTH_CHECK = "manageHealthCheck";
  @SerializedName(SERIALIZED_NAME_MANAGE_HEALTH_CHECK)
  private Boolean manageHealthCheck;

  public static final String SERIALIZED_NAME_SCHEMATIC = "schematic";
  @SerializedName(SERIALIZED_NAME_SCHEMATIC)
  private V1beta1PolicyDefinitionSpecSchematic schematic;


  public V1beta1PolicyDefinitionSpec definitionRef(V1beta1WorkflowStepDefinitionSpecDefinitionRef definitionRef) {
    
    this.definitionRef = definitionRef;
    return this;
  }

   /**
   * Get definitionRef
   * @return definitionRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkflowStepDefinitionSpecDefinitionRef getDefinitionRef() {
    return definitionRef;
  }


  public void setDefinitionRef(V1beta1WorkflowStepDefinitionSpecDefinitionRef definitionRef) {
    this.definitionRef = definitionRef;
  }


  public V1beta1PolicyDefinitionSpec manageHealthCheck(Boolean manageHealthCheck) {
    
    this.manageHealthCheck = manageHealthCheck;
    return this;
  }

   /**
   * ManageHealthCheck means the policy will handle health checking and skip application controller built-in health checking.
   * @return manageHealthCheck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ManageHealthCheck means the policy will handle health checking and skip application controller built-in health checking.")

  public Boolean getManageHealthCheck() {
    return manageHealthCheck;
  }


  public void setManageHealthCheck(Boolean manageHealthCheck) {
    this.manageHealthCheck = manageHealthCheck;
  }


  public V1beta1PolicyDefinitionSpec schematic(V1beta1PolicyDefinitionSpecSchematic schematic) {
    
    this.schematic = schematic;
    return this;
  }

   /**
   * Get schematic
   * @return schematic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1PolicyDefinitionSpecSchematic getSchematic() {
    return schematic;
  }


  public void setSchematic(V1beta1PolicyDefinitionSpecSchematic schematic) {
    this.schematic = schematic;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1PolicyDefinitionSpec v1beta1PolicyDefinitionSpec = (V1beta1PolicyDefinitionSpec) o;
    return Objects.equals(this.definitionRef, v1beta1PolicyDefinitionSpec.definitionRef) &&
        Objects.equals(this.manageHealthCheck, v1beta1PolicyDefinitionSpec.manageHealthCheck) &&
        Objects.equals(this.schematic, v1beta1PolicyDefinitionSpec.schematic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definitionRef, manageHealthCheck, schematic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1PolicyDefinitionSpec {\n");
    sb.append("    definitionRef: ").append(toIndentedString(definitionRef)).append("\n");
    sb.append("    manageHealthCheck: ").append(toIndentedString(manageHealthCheck)).append("\n");
    sb.append("    schematic: ").append(toIndentedString(schematic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

