/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ComponentDefinitionSpecWorkloadDefinition;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Workload is a workload type descriptor
 */
@ApiModel(description = "Workload is a workload type descriptor")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ComponentDefinitionSpecWorkload {
  public static final String SERIALIZED_NAME_DEFINITION = "definition";
  @SerializedName(SERIALIZED_NAME_DEFINITION)
  private V1beta1ComponentDefinitionSpecWorkloadDefinition definition;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1beta1ComponentDefinitionSpecWorkload definition(V1beta1ComponentDefinitionSpecWorkloadDefinition definition) {
    
    this.definition = definition;
    return this;
  }

   /**
   * Get definition
   * @return definition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ComponentDefinitionSpecWorkloadDefinition getDefinition() {
    return definition;
  }


  public void setDefinition(V1beta1ComponentDefinitionSpecWorkloadDefinition definition) {
    this.definition = definition;
  }


  public V1beta1ComponentDefinitionSpecWorkload type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type ref to a WorkloadDefinition via name
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type ref to a WorkloadDefinition via name")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ComponentDefinitionSpecWorkload v1beta1ComponentDefinitionSpecWorkload = (V1beta1ComponentDefinitionSpecWorkload) o;
    return Objects.equals(this.definition, v1beta1ComponentDefinitionSpecWorkload.definition) &&
        Objects.equals(this.type, v1beta1ComponentDefinitionSpecWorkload.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(definition, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ComponentDefinitionSpecWorkload {\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

