/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationRevisionStatusWorkflow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ApplicationRevisionStatus is the status of ApplicationRevision
 */
@ApiModel(description = "ApplicationRevisionStatus is the status of ApplicationRevision")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationRevisionStatus {
  public static final String SERIALIZED_NAME_SUCCEEDED = "succeeded";
  @SerializedName(SERIALIZED_NAME_SUCCEEDED)
  private Boolean succeeded;

  public static final String SERIALIZED_NAME_WORKFLOW = "workflow";
  @SerializedName(SERIALIZED_NAME_WORKFLOW)
  private V1beta1ApplicationRevisionStatusWorkflow workflow;

  public static final String SERIALIZED_NAME_WORKFLOW_CONTEXT = "workflowContext";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_CONTEXT)
  private Map<String, String> workflowContext = null;


  public V1beta1ApplicationRevisionStatus succeeded(Boolean succeeded) {
    
    this.succeeded = succeeded;
    return this;
  }

   /**
   * Succeeded records if the workflow finished running with success
   * @return succeeded
  **/
  @ApiModelProperty(required = true, value = "Succeeded records if the workflow finished running with success")

  public Boolean getSucceeded() {
    return succeeded;
  }


  public void setSucceeded(Boolean succeeded) {
    this.succeeded = succeeded;
  }


  public V1beta1ApplicationRevisionStatus workflow(V1beta1ApplicationRevisionStatusWorkflow workflow) {
    
    this.workflow = workflow;
    return this;
  }

   /**
   * Get workflow
   * @return workflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationRevisionStatusWorkflow getWorkflow() {
    return workflow;
  }


  public void setWorkflow(V1beta1ApplicationRevisionStatusWorkflow workflow) {
    this.workflow = workflow;
  }


  public V1beta1ApplicationRevisionStatus workflowContext(Map<String, String> workflowContext) {
    
    this.workflowContext = workflowContext;
    return this;
  }

  public V1beta1ApplicationRevisionStatus putWorkflowContextItem(String key, String workflowContextItem) {
    if (this.workflowContext == null) {
      this.workflowContext = new HashMap<>();
    }
    this.workflowContext.put(key, workflowContextItem);
    return this;
  }

   /**
   * Record the context values to the revision.
   * @return workflowContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Record the context values to the revision.")

  public Map<String, String> getWorkflowContext() {
    return workflowContext;
  }


  public void setWorkflowContext(Map<String, String> workflowContext) {
    this.workflowContext = workflowContext;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationRevisionStatus v1beta1ApplicationRevisionStatus = (V1beta1ApplicationRevisionStatus) o;
    return Objects.equals(this.succeeded, v1beta1ApplicationRevisionStatus.succeeded) &&
        Objects.equals(this.workflow, v1beta1ApplicationRevisionStatus.workflow) &&
        Objects.equals(this.workflowContext, v1beta1ApplicationRevisionStatus.workflowContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(succeeded, workflow, workflowContext);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationRevisionStatus {\n");
    sb.append("    succeeded: ").append(toIndentedString(succeeded)).append("\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("    workflowContext: ").append(toIndentedString(workflowContext)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

