/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationSpecInputs;
import dev.oam.core.models.V1beta1ApplicationSpecOutputs;
import dev.oam.core.models.V1beta1ApplicationSpecTraits;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApplicationComponent describe the component of application
 */
@ApiModel(description = "ApplicationComponent describe the component of application")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationSpecComponents {
  public static final String SERIALIZED_NAME_DEPENDS_ON = "dependsOn";
  @SerializedName(SERIALIZED_NAME_DEPENDS_ON)
  private List<String> dependsOn = null;

  public static final String SERIALIZED_NAME_EXTERNAL_REVISION = "externalRevision";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_REVISION)
  private String externalRevision;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<V1beta1ApplicationSpecInputs> inputs = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OUTPUTS = "outputs";
  @SerializedName(SERIALIZED_NAME_OUTPUTS)
  private List<V1beta1ApplicationSpecOutputs> outputs = null;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private Object properties;

  public static final String SERIALIZED_NAME_SCOPES = "scopes";
  @SerializedName(SERIALIZED_NAME_SCOPES)
  private Object scopes;

  public static final String SERIALIZED_NAME_TRAITS = "traits";
  @SerializedName(SERIALIZED_NAME_TRAITS)
  private List<V1beta1ApplicationSpecTraits> traits = null;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1beta1ApplicationSpecComponents dependsOn(List<String> dependsOn) {
    
    this.dependsOn = dependsOn;
    return this;
  }

  public V1beta1ApplicationSpecComponents addDependsOnItem(String dependsOnItem) {
    if (this.dependsOn == null) {
      this.dependsOn = new ArrayList<>();
    }
    this.dependsOn.add(dependsOnItem);
    return this;
  }

   /**
   * Get dependsOn
   * @return dependsOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDependsOn() {
    return dependsOn;
  }


  public void setDependsOn(List<String> dependsOn) {
    this.dependsOn = dependsOn;
  }


  public V1beta1ApplicationSpecComponents externalRevision(String externalRevision) {
    
    this.externalRevision = externalRevision;
    return this;
  }

   /**
   * ExternalRevision specified the component revisionName
   * @return externalRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ExternalRevision specified the component revisionName")

  public String getExternalRevision() {
    return externalRevision;
  }


  public void setExternalRevision(String externalRevision) {
    this.externalRevision = externalRevision;
  }


  public V1beta1ApplicationSpecComponents inputs(List<V1beta1ApplicationSpecInputs> inputs) {
    
    this.inputs = inputs;
    return this;
  }

  public V1beta1ApplicationSpecComponents addInputsItem(V1beta1ApplicationSpecInputs inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * StepInputs defines variable input of WorkflowStep
   * @return inputs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "StepInputs defines variable input of WorkflowStep")

  public List<V1beta1ApplicationSpecInputs> getInputs() {
    return inputs;
  }


  public void setInputs(List<V1beta1ApplicationSpecInputs> inputs) {
    this.inputs = inputs;
  }


  public V1beta1ApplicationSpecComponents name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1beta1ApplicationSpecComponents outputs(List<V1beta1ApplicationSpecOutputs> outputs) {
    
    this.outputs = outputs;
    return this;
  }

  public V1beta1ApplicationSpecComponents addOutputsItem(V1beta1ApplicationSpecOutputs outputsItem) {
    if (this.outputs == null) {
      this.outputs = new ArrayList<>();
    }
    this.outputs.add(outputsItem);
    return this;
  }

   /**
   * StepOutputs defines output variable of WorkflowStep
   * @return outputs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "StepOutputs defines output variable of WorkflowStep")

  public List<V1beta1ApplicationSpecOutputs> getOutputs() {
    return outputs;
  }


  public void setOutputs(List<V1beta1ApplicationSpecOutputs> outputs) {
    this.outputs = outputs;
  }


  public V1beta1ApplicationSpecComponents properties(Object properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getProperties() {
    return properties;
  }


  public void setProperties(Object properties) {
    this.properties = properties;
  }


  public V1beta1ApplicationSpecComponents scopes(Object scopes) {
    
    this.scopes = scopes;
    return this;
  }

   /**
   * scopes in ApplicationComponent defines the component-level scopes the format is &lt;scope-type:scope-instance-name&gt; pairs, the key represents type of &#x60;ScopeDefinition&#x60; while the value represent the name of scope instance.
   * @return scopes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "scopes in ApplicationComponent defines the component-level scopes the format is <scope-type:scope-instance-name> pairs, the key represents type of `ScopeDefinition` while the value represent the name of scope instance.")

  public Object getScopes() {
    return scopes;
  }


  public void setScopes(Object scopes) {
    this.scopes = scopes;
  }


  public V1beta1ApplicationSpecComponents traits(List<V1beta1ApplicationSpecTraits> traits) {
    
    this.traits = traits;
    return this;
  }

  public V1beta1ApplicationSpecComponents addTraitsItem(V1beta1ApplicationSpecTraits traitsItem) {
    if (this.traits == null) {
      this.traits = new ArrayList<>();
    }
    this.traits.add(traitsItem);
    return this;
  }

   /**
   * Traits define the trait of one component, the type must be array to keep the order.
   * @return traits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Traits define the trait of one component, the type must be array to keep the order.")

  public List<V1beta1ApplicationSpecTraits> getTraits() {
    return traits;
  }


  public void setTraits(List<V1beta1ApplicationSpecTraits> traits) {
    this.traits = traits;
  }


  public V1beta1ApplicationSpecComponents type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationSpecComponents v1beta1ApplicationSpecComponents = (V1beta1ApplicationSpecComponents) o;
    return Objects.equals(this.dependsOn, v1beta1ApplicationSpecComponents.dependsOn) &&
        Objects.equals(this.externalRevision, v1beta1ApplicationSpecComponents.externalRevision) &&
        Objects.equals(this.inputs, v1beta1ApplicationSpecComponents.inputs) &&
        Objects.equals(this.name, v1beta1ApplicationSpecComponents.name) &&
        Objects.equals(this.outputs, v1beta1ApplicationSpecComponents.outputs) &&
        Objects.equals(this.properties, v1beta1ApplicationSpecComponents.properties) &&
        Objects.equals(this.scopes, v1beta1ApplicationSpecComponents.scopes) &&
        Objects.equals(this.traits, v1beta1ApplicationSpecComponents.traits) &&
        Objects.equals(this.type, v1beta1ApplicationSpecComponents.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dependsOn, externalRevision, inputs, name, outputs, properties, scopes, traits, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationSpecComponents {\n");
    sb.append("    dependsOn: ").append(toIndentedString(dependsOn)).append("\n");
    sb.append("    externalRevision: ").append(toIndentedString(externalRevision)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    traits: ").append(toIndentedString(traits)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

