/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecApplication;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecComponentDefinitions;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecCompression;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecPolicies;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecPolicyDefinitions;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecTraitDefinitions;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecWorkflow;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecWorkflowStepDefinitions;
import dev.oam.core.models.V1beta1ApplicationRevisionSpecWorkloadDefinitions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ApplicationRevisionSpec is the spec of ApplicationRevision
 */
@ApiModel(description = "ApplicationRevisionSpec is the spec of ApplicationRevision")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationRevisionSpec {
  public static final String SERIALIZED_NAME_APPLICATION = "application";
  @SerializedName(SERIALIZED_NAME_APPLICATION)
  private V1beta1ApplicationRevisionSpecApplication application;

  public static final String SERIALIZED_NAME_COMPONENT_DEFINITIONS = "componentDefinitions";
  @SerializedName(SERIALIZED_NAME_COMPONENT_DEFINITIONS)
  private Map<String, V1beta1ApplicationRevisionSpecComponentDefinitions> componentDefinitions = null;

  public static final String SERIALIZED_NAME_COMPRESSION = "compression";
  @SerializedName(SERIALIZED_NAME_COMPRESSION)
  private V1beta1ApplicationRevisionSpecCompression compression;

  public static final String SERIALIZED_NAME_POLICIES = "policies";
  @SerializedName(SERIALIZED_NAME_POLICIES)
  private Map<String, V1beta1ApplicationRevisionSpecPolicies> policies = null;

  public static final String SERIALIZED_NAME_POLICY_DEFINITIONS = "policyDefinitions";
  @SerializedName(SERIALIZED_NAME_POLICY_DEFINITIONS)
  private Map<String, V1beta1ApplicationRevisionSpecPolicyDefinitions> policyDefinitions = null;

  public static final String SERIALIZED_NAME_REFERRED_OBJECTS = "referredObjects";
  @SerializedName(SERIALIZED_NAME_REFERRED_OBJECTS)
  private Object referredObjects;

  public static final String SERIALIZED_NAME_TRAIT_DEFINITIONS = "traitDefinitions";
  @SerializedName(SERIALIZED_NAME_TRAIT_DEFINITIONS)
  private Map<String, V1beta1ApplicationRevisionSpecTraitDefinitions> traitDefinitions = null;

  public static final String SERIALIZED_NAME_WORKFLOW = "workflow";
  @SerializedName(SERIALIZED_NAME_WORKFLOW)
  private V1beta1ApplicationRevisionSpecWorkflow workflow;

  public static final String SERIALIZED_NAME_WORKFLOW_STEP_DEFINITIONS = "workflowStepDefinitions";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_STEP_DEFINITIONS)
  private Map<String, V1beta1ApplicationRevisionSpecWorkflowStepDefinitions> workflowStepDefinitions = null;

  public static final String SERIALIZED_NAME_WORKLOAD_DEFINITIONS = "workloadDefinitions";
  @SerializedName(SERIALIZED_NAME_WORKLOAD_DEFINITIONS)
  private Map<String, V1beta1ApplicationRevisionSpecWorkloadDefinitions> workloadDefinitions = null;


  public V1beta1ApplicationRevisionSpec application(V1beta1ApplicationRevisionSpecApplication application) {
    
    this.application = application;
    return this;
  }

   /**
   * Get application
   * @return application
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1ApplicationRevisionSpecApplication getApplication() {
    return application;
  }


  public void setApplication(V1beta1ApplicationRevisionSpecApplication application) {
    this.application = application;
  }


  public V1beta1ApplicationRevisionSpec componentDefinitions(Map<String, V1beta1ApplicationRevisionSpecComponentDefinitions> componentDefinitions) {
    
    this.componentDefinitions = componentDefinitions;
    return this;
  }

  public V1beta1ApplicationRevisionSpec putComponentDefinitionsItem(String key, V1beta1ApplicationRevisionSpecComponentDefinitions componentDefinitionsItem) {
    if (this.componentDefinitions == null) {
      this.componentDefinitions = new HashMap<>();
    }
    this.componentDefinitions.put(key, componentDefinitionsItem);
    return this;
  }

   /**
   * ComponentDefinitions records the snapshot of the componentDefinitions related with the created/modified Application
   * @return componentDefinitions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ComponentDefinitions records the snapshot of the componentDefinitions related with the created/modified Application")

  public Map<String, V1beta1ApplicationRevisionSpecComponentDefinitions> getComponentDefinitions() {
    return componentDefinitions;
  }


  public void setComponentDefinitions(Map<String, V1beta1ApplicationRevisionSpecComponentDefinitions> componentDefinitions) {
    this.componentDefinitions = componentDefinitions;
  }


  public V1beta1ApplicationRevisionSpec compression(V1beta1ApplicationRevisionSpecCompression compression) {
    
    this.compression = compression;
    return this;
  }

   /**
   * Get compression
   * @return compression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationRevisionSpecCompression getCompression() {
    return compression;
  }


  public void setCompression(V1beta1ApplicationRevisionSpecCompression compression) {
    this.compression = compression;
  }


  public V1beta1ApplicationRevisionSpec policies(Map<String, V1beta1ApplicationRevisionSpecPolicies> policies) {
    
    this.policies = policies;
    return this;
  }

  public V1beta1ApplicationRevisionSpec putPoliciesItem(String key, V1beta1ApplicationRevisionSpecPolicies policiesItem) {
    if (this.policies == null) {
      this.policies = new HashMap<>();
    }
    this.policies.put(key, policiesItem);
    return this;
  }

   /**
   * Policies records the external policies
   * @return policies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Policies records the external policies")

  public Map<String, V1beta1ApplicationRevisionSpecPolicies> getPolicies() {
    return policies;
  }


  public void setPolicies(Map<String, V1beta1ApplicationRevisionSpecPolicies> policies) {
    this.policies = policies;
  }


  public V1beta1ApplicationRevisionSpec policyDefinitions(Map<String, V1beta1ApplicationRevisionSpecPolicyDefinitions> policyDefinitions) {
    
    this.policyDefinitions = policyDefinitions;
    return this;
  }

  public V1beta1ApplicationRevisionSpec putPolicyDefinitionsItem(String key, V1beta1ApplicationRevisionSpecPolicyDefinitions policyDefinitionsItem) {
    if (this.policyDefinitions == null) {
      this.policyDefinitions = new HashMap<>();
    }
    this.policyDefinitions.put(key, policyDefinitionsItem);
    return this;
  }

   /**
   * PolicyDefinitions records the snapshot of the PolicyDefinitions related with the created/modified Application
   * @return policyDefinitions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PolicyDefinitions records the snapshot of the PolicyDefinitions related with the created/modified Application")

  public Map<String, V1beta1ApplicationRevisionSpecPolicyDefinitions> getPolicyDefinitions() {
    return policyDefinitions;
  }


  public void setPolicyDefinitions(Map<String, V1beta1ApplicationRevisionSpecPolicyDefinitions> policyDefinitions) {
    this.policyDefinitions = policyDefinitions;
  }


  public V1beta1ApplicationRevisionSpec referredObjects(Object referredObjects) {
    
    this.referredObjects = referredObjects;
    return this;
  }

   /**
   * ReferredObjects records the referred objects used in the ref-object typed components
   * @return referredObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ReferredObjects records the referred objects used in the ref-object typed components")

  public Object getReferredObjects() {
    return referredObjects;
  }


  public void setReferredObjects(Object referredObjects) {
    this.referredObjects = referredObjects;
  }


  public V1beta1ApplicationRevisionSpec traitDefinitions(Map<String, V1beta1ApplicationRevisionSpecTraitDefinitions> traitDefinitions) {
    
    this.traitDefinitions = traitDefinitions;
    return this;
  }

  public V1beta1ApplicationRevisionSpec putTraitDefinitionsItem(String key, V1beta1ApplicationRevisionSpecTraitDefinitions traitDefinitionsItem) {
    if (this.traitDefinitions == null) {
      this.traitDefinitions = new HashMap<>();
    }
    this.traitDefinitions.put(key, traitDefinitionsItem);
    return this;
  }

   /**
   * TraitDefinitions records the snapshot of the traitDefinitions related with the created/modified Application
   * @return traitDefinitions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TraitDefinitions records the snapshot of the traitDefinitions related with the created/modified Application")

  public Map<String, V1beta1ApplicationRevisionSpecTraitDefinitions> getTraitDefinitions() {
    return traitDefinitions;
  }


  public void setTraitDefinitions(Map<String, V1beta1ApplicationRevisionSpecTraitDefinitions> traitDefinitions) {
    this.traitDefinitions = traitDefinitions;
  }


  public V1beta1ApplicationRevisionSpec workflow(V1beta1ApplicationRevisionSpecWorkflow workflow) {
    
    this.workflow = workflow;
    return this;
  }

   /**
   * Get workflow
   * @return workflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationRevisionSpecWorkflow getWorkflow() {
    return workflow;
  }


  public void setWorkflow(V1beta1ApplicationRevisionSpecWorkflow workflow) {
    this.workflow = workflow;
  }


  public V1beta1ApplicationRevisionSpec workflowStepDefinitions(Map<String, V1beta1ApplicationRevisionSpecWorkflowStepDefinitions> workflowStepDefinitions) {
    
    this.workflowStepDefinitions = workflowStepDefinitions;
    return this;
  }

  public V1beta1ApplicationRevisionSpec putWorkflowStepDefinitionsItem(String key, V1beta1ApplicationRevisionSpecWorkflowStepDefinitions workflowStepDefinitionsItem) {
    if (this.workflowStepDefinitions == null) {
      this.workflowStepDefinitions = new HashMap<>();
    }
    this.workflowStepDefinitions.put(key, workflowStepDefinitionsItem);
    return this;
  }

   /**
   * WorkflowStepDefinitions records the snapshot of the WorkflowStepDefinitions related with the created/modified Application
   * @return workflowStepDefinitions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "WorkflowStepDefinitions records the snapshot of the WorkflowStepDefinitions related with the created/modified Application")

  public Map<String, V1beta1ApplicationRevisionSpecWorkflowStepDefinitions> getWorkflowStepDefinitions() {
    return workflowStepDefinitions;
  }


  public void setWorkflowStepDefinitions(Map<String, V1beta1ApplicationRevisionSpecWorkflowStepDefinitions> workflowStepDefinitions) {
    this.workflowStepDefinitions = workflowStepDefinitions;
  }


  public V1beta1ApplicationRevisionSpec workloadDefinitions(Map<String, V1beta1ApplicationRevisionSpecWorkloadDefinitions> workloadDefinitions) {
    
    this.workloadDefinitions = workloadDefinitions;
    return this;
  }

  public V1beta1ApplicationRevisionSpec putWorkloadDefinitionsItem(String key, V1beta1ApplicationRevisionSpecWorkloadDefinitions workloadDefinitionsItem) {
    if (this.workloadDefinitions == null) {
      this.workloadDefinitions = new HashMap<>();
    }
    this.workloadDefinitions.put(key, workloadDefinitionsItem);
    return this;
  }

   /**
   * WorkloadDefinitions records the snapshot of the workloadDefinitions related with the created/modified Application
   * @return workloadDefinitions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "WorkloadDefinitions records the snapshot of the workloadDefinitions related with the created/modified Application")

  public Map<String, V1beta1ApplicationRevisionSpecWorkloadDefinitions> getWorkloadDefinitions() {
    return workloadDefinitions;
  }


  public void setWorkloadDefinitions(Map<String, V1beta1ApplicationRevisionSpecWorkloadDefinitions> workloadDefinitions) {
    this.workloadDefinitions = workloadDefinitions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationRevisionSpec v1beta1ApplicationRevisionSpec = (V1beta1ApplicationRevisionSpec) o;
    return Objects.equals(this.application, v1beta1ApplicationRevisionSpec.application) &&
        Objects.equals(this.componentDefinitions, v1beta1ApplicationRevisionSpec.componentDefinitions) &&
        Objects.equals(this.compression, v1beta1ApplicationRevisionSpec.compression) &&
        Objects.equals(this.policies, v1beta1ApplicationRevisionSpec.policies) &&
        Objects.equals(this.policyDefinitions, v1beta1ApplicationRevisionSpec.policyDefinitions) &&
        Objects.equals(this.referredObjects, v1beta1ApplicationRevisionSpec.referredObjects) &&
        Objects.equals(this.traitDefinitions, v1beta1ApplicationRevisionSpec.traitDefinitions) &&
        Objects.equals(this.workflow, v1beta1ApplicationRevisionSpec.workflow) &&
        Objects.equals(this.workflowStepDefinitions, v1beta1ApplicationRevisionSpec.workflowStepDefinitions) &&
        Objects.equals(this.workloadDefinitions, v1beta1ApplicationRevisionSpec.workloadDefinitions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(application, componentDefinitions, compression, policies, policyDefinitions, referredObjects, traitDefinitions, workflow, workflowStepDefinitions, workloadDefinitions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationRevisionSpec {\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    componentDefinitions: ").append(toIndentedString(componentDefinitions)).append("\n");
    sb.append("    compression: ").append(toIndentedString(compression)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    policyDefinitions: ").append(toIndentedString(policyDefinitions)).append("\n");
    sb.append("    referredObjects: ").append(toIndentedString(referredObjects)).append("\n");
    sb.append("    traitDefinitions: ").append(toIndentedString(traitDefinitions)).append("\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("    workflowStepDefinitions: ").append(toIndentedString(workflowStepDefinitions)).append("\n");
    sb.append("    workloadDefinitions: ").append(toIndentedString(workloadDefinitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

