/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationStatusComponents;
import dev.oam.core.models.V1beta1ApplicationStatusTraits;
import dev.oam.core.models.V1beta1ApplicationStatusWorkloadDefinition;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApplicationComponentStatus record the health status of App component
 */
@ApiModel(description = "ApplicationComponentStatus record the health status of App component")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationStatusServices {
  public static final String SERIALIZED_NAME_CLUSTER = "cluster";
  @SerializedName(SERIALIZED_NAME_CLUSTER)
  private String cluster;

  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private String env;

  public static final String SERIALIZED_NAME_HEALTHY = "healthy";
  @SerializedName(SERIALIZED_NAME_HEALTHY)
  private Boolean healthy;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;

  public static final String SERIALIZED_NAME_SCOPES = "scopes";
  @SerializedName(SERIALIZED_NAME_SCOPES)
  private List<V1beta1ApplicationStatusComponents> scopes = null;

  public static final String SERIALIZED_NAME_TRAITS = "traits";
  @SerializedName(SERIALIZED_NAME_TRAITS)
  private List<V1beta1ApplicationStatusTraits> traits = null;

  public static final String SERIALIZED_NAME_WORKLOAD_DEFINITION = "workloadDefinition";
  @SerializedName(SERIALIZED_NAME_WORKLOAD_DEFINITION)
  private V1beta1ApplicationStatusWorkloadDefinition workloadDefinition;


  public V1beta1ApplicationStatusServices cluster(String cluster) {
    
    this.cluster = cluster;
    return this;
  }

   /**
   * Get cluster
   * @return cluster
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCluster() {
    return cluster;
  }


  public void setCluster(String cluster) {
    this.cluster = cluster;
  }


  public V1beta1ApplicationStatusServices env(String env) {
    
    this.env = env;
    return this;
  }

   /**
   * Get env
   * @return env
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEnv() {
    return env;
  }


  public void setEnv(String env) {
    this.env = env;
  }


  public V1beta1ApplicationStatusServices healthy(Boolean healthy) {
    
    this.healthy = healthy;
    return this;
  }

   /**
   * Get healthy
   * @return healthy
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getHealthy() {
    return healthy;
  }


  public void setHealthy(Boolean healthy) {
    this.healthy = healthy;
  }


  public V1beta1ApplicationStatusServices message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public V1beta1ApplicationStatusServices name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1beta1ApplicationStatusServices namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * Get namespace
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  public V1beta1ApplicationStatusServices scopes(List<V1beta1ApplicationStatusComponents> scopes) {
    
    this.scopes = scopes;
    return this;
  }

  public V1beta1ApplicationStatusServices addScopesItem(V1beta1ApplicationStatusComponents scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

   /**
   * Get scopes
   * @return scopes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1ApplicationStatusComponents> getScopes() {
    return scopes;
  }


  public void setScopes(List<V1beta1ApplicationStatusComponents> scopes) {
    this.scopes = scopes;
  }


  public V1beta1ApplicationStatusServices traits(List<V1beta1ApplicationStatusTraits> traits) {
    
    this.traits = traits;
    return this;
  }

  public V1beta1ApplicationStatusServices addTraitsItem(V1beta1ApplicationStatusTraits traitsItem) {
    if (this.traits == null) {
      this.traits = new ArrayList<>();
    }
    this.traits.add(traitsItem);
    return this;
  }

   /**
   * Get traits
   * @return traits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1ApplicationStatusTraits> getTraits() {
    return traits;
  }


  public void setTraits(List<V1beta1ApplicationStatusTraits> traits) {
    this.traits = traits;
  }


  public V1beta1ApplicationStatusServices workloadDefinition(V1beta1ApplicationStatusWorkloadDefinition workloadDefinition) {
    
    this.workloadDefinition = workloadDefinition;
    return this;
  }

   /**
   * Get workloadDefinition
   * @return workloadDefinition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationStatusWorkloadDefinition getWorkloadDefinition() {
    return workloadDefinition;
  }


  public void setWorkloadDefinition(V1beta1ApplicationStatusWorkloadDefinition workloadDefinition) {
    this.workloadDefinition = workloadDefinition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationStatusServices v1beta1ApplicationStatusServices = (V1beta1ApplicationStatusServices) o;
    return Objects.equals(this.cluster, v1beta1ApplicationStatusServices.cluster) &&
        Objects.equals(this.env, v1beta1ApplicationStatusServices.env) &&
        Objects.equals(this.healthy, v1beta1ApplicationStatusServices.healthy) &&
        Objects.equals(this.message, v1beta1ApplicationStatusServices.message) &&
        Objects.equals(this.name, v1beta1ApplicationStatusServices.name) &&
        Objects.equals(this.namespace, v1beta1ApplicationStatusServices.namespace) &&
        Objects.equals(this.scopes, v1beta1ApplicationStatusServices.scopes) &&
        Objects.equals(this.traits, v1beta1ApplicationStatusServices.traits) &&
        Objects.equals(this.workloadDefinition, v1beta1ApplicationStatusServices.workloadDefinition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cluster, env, healthy, message, name, namespace, scopes, traits, workloadDefinition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationStatusServices {\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    healthy: ").append(toIndentedString(healthy)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    traits: ").append(toIndentedString(traits)).append("\n");
    sb.append("    workloadDefinition: ").append(toIndentedString(workloadDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

