/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1WorkflowStepDefinitionStatusConditions;
import dev.oam.core.models.V1beta1WorkflowStepDefinitionStatusLatestRevision;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WorkflowStepDefinitionStatus is the status of WorkflowStepDefinition
 */
@ApiModel(description = "WorkflowStepDefinitionStatus is the status of WorkflowStepDefinition")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1WorkflowStepDefinitionStatus {
  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1beta1WorkflowStepDefinitionStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_CONFIG_MAP_REF = "configMapRef";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP_REF)
  private String configMapRef;

  public static final String SERIALIZED_NAME_LATEST_REVISION = "latestRevision";
  @SerializedName(SERIALIZED_NAME_LATEST_REVISION)
  private V1beta1WorkflowStepDefinitionStatusLatestRevision latestRevision;


  public V1beta1WorkflowStepDefinitionStatus conditions(List<V1beta1WorkflowStepDefinitionStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1beta1WorkflowStepDefinitionStatus addConditionsItem(V1beta1WorkflowStepDefinitionStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions of the resource.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Conditions of the resource.")

  public List<V1beta1WorkflowStepDefinitionStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1beta1WorkflowStepDefinitionStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1beta1WorkflowStepDefinitionStatus configMapRef(String configMapRef) {
    
    this.configMapRef = configMapRef;
    return this;
  }

   /**
   * ConfigMapRef refer to a ConfigMap which contains OpenAPI V3 JSON schema of Component parameters.
   * @return configMapRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ConfigMapRef refer to a ConfigMap which contains OpenAPI V3 JSON schema of Component parameters.")

  public String getConfigMapRef() {
    return configMapRef;
  }


  public void setConfigMapRef(String configMapRef) {
    this.configMapRef = configMapRef;
  }


  public V1beta1WorkflowStepDefinitionStatus latestRevision(V1beta1WorkflowStepDefinitionStatusLatestRevision latestRevision) {
    
    this.latestRevision = latestRevision;
    return this;
  }

   /**
   * Get latestRevision
   * @return latestRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkflowStepDefinitionStatusLatestRevision getLatestRevision() {
    return latestRevision;
  }


  public void setLatestRevision(V1beta1WorkflowStepDefinitionStatusLatestRevision latestRevision) {
    this.latestRevision = latestRevision;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkflowStepDefinitionStatus v1beta1WorkflowStepDefinitionStatus = (V1beta1WorkflowStepDefinitionStatus) o;
    return Objects.equals(this.conditions, v1beta1WorkflowStepDefinitionStatus.conditions) &&
        Objects.equals(this.configMapRef, v1beta1WorkflowStepDefinitionStatus.configMapRef) &&
        Objects.equals(this.latestRevision, v1beta1WorkflowStepDefinitionStatus.latestRevision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conditions, configMapRef, latestRevision);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkflowStepDefinitionStatus {\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    configMapRef: ").append(toIndentedString(configMapRef)).append("\n");
    sb.append("    latestRevision: ").append(toIndentedString(latestRevision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

