/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationSpecComponents;
import dev.oam.core.models.V1beta1ApplicationSpecPolicies;
import dev.oam.core.models.V1beta1ApplicationSpecWorkflow;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApplicationSpec is the spec of Application
 */
@ApiModel(description = "ApplicationSpec is the spec of Application")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationSpec {
  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  private List<V1beta1ApplicationSpecComponents> components = new ArrayList<>();

  public static final String SERIALIZED_NAME_POLICIES = "policies";
  @SerializedName(SERIALIZED_NAME_POLICIES)
  private List<V1beta1ApplicationSpecPolicies> policies = null;

  public static final String SERIALIZED_NAME_WORKFLOW = "workflow";
  @SerializedName(SERIALIZED_NAME_WORKFLOW)
  private V1beta1ApplicationSpecWorkflow workflow;


  public V1beta1ApplicationSpec components(List<V1beta1ApplicationSpecComponents> components) {
    
    this.components = components;
    return this;
  }

  public V1beta1ApplicationSpec addComponentsItem(V1beta1ApplicationSpecComponents componentsItem) {
    this.components.add(componentsItem);
    return this;
  }

   /**
   * Get components
   * @return components
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1beta1ApplicationSpecComponents> getComponents() {
    return components;
  }


  public void setComponents(List<V1beta1ApplicationSpecComponents> components) {
    this.components = components;
  }


  public V1beta1ApplicationSpec policies(List<V1beta1ApplicationSpecPolicies> policies) {
    
    this.policies = policies;
    return this;
  }

  public V1beta1ApplicationSpec addPoliciesItem(V1beta1ApplicationSpecPolicies policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Policies defines the global policies for all components in the app, e.g. security, metrics, gitops, multi-cluster placement rules, etc. Policies are applied after components are rendered and before workflow steps are executed.
   * @return policies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Policies defines the global policies for all components in the app, e.g. security, metrics, gitops, multi-cluster placement rules, etc. Policies are applied after components are rendered and before workflow steps are executed.")

  public List<V1beta1ApplicationSpecPolicies> getPolicies() {
    return policies;
  }


  public void setPolicies(List<V1beta1ApplicationSpecPolicies> policies) {
    this.policies = policies;
  }


  public V1beta1ApplicationSpec workflow(V1beta1ApplicationSpecWorkflow workflow) {
    
    this.workflow = workflow;
    return this;
  }

   /**
   * Get workflow
   * @return workflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationSpecWorkflow getWorkflow() {
    return workflow;
  }


  public void setWorkflow(V1beta1ApplicationSpecWorkflow workflow) {
    this.workflow = workflow;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationSpec v1beta1ApplicationSpec = (V1beta1ApplicationSpec) o;
    return Objects.equals(this.components, v1beta1ApplicationSpec.components) &&
        Objects.equals(this.policies, v1beta1ApplicationSpec.policies) &&
        Objects.equals(this.workflow, v1beta1ApplicationSpec.workflow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, policies, workflow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationSpec {\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

