/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import dev.oam.core.models.V1beta1ApplicationStatusAppliedResources;
import dev.oam.core.models.V1beta1ApplicationStatusComponents;
import dev.oam.core.models.V1beta1ApplicationStatusLatestRevision;
import dev.oam.core.models.V1beta1ApplicationStatusPolicy;
import dev.oam.core.models.V1beta1ApplicationStatusServices;
import dev.oam.core.models.V1beta1ApplicationStatusWorkflow;
import dev.oam.core.models.V1beta1WorkflowStepDefinitionStatusConditions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * AppStatus defines the observed state of Application
 */
@ApiModel(description = "AppStatus defines the observed state of Application")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationStatus {
  public static final String SERIALIZED_NAME_APPLIED_RESOURCES = "appliedResources";
  @SerializedName(SERIALIZED_NAME_APPLIED_RESOURCES)
  private List<V1beta1ApplicationStatusAppliedResources> appliedResources = null;

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  private List<V1beta1ApplicationStatusComponents> components = null;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  private List<V1beta1WorkflowStepDefinitionStatusConditions> conditions = null;

  public static final String SERIALIZED_NAME_LATEST_REVISION = "latestRevision";
  @SerializedName(SERIALIZED_NAME_LATEST_REVISION)
  private V1beta1ApplicationStatusLatestRevision latestRevision;

  public static final String SERIALIZED_NAME_OBSERVED_GENERATION = "observedGeneration";
  @SerializedName(SERIALIZED_NAME_OBSERVED_GENERATION)
  private Long observedGeneration;

  public static final String SERIALIZED_NAME_POLICY = "policy";
  @SerializedName(SERIALIZED_NAME_POLICY)
  private List<V1beta1ApplicationStatusPolicy> policy = null;

  public static final String SERIALIZED_NAME_SERVICES = "services";
  @SerializedName(SERIALIZED_NAME_SERVICES)
  private List<V1beta1ApplicationStatusServices> services = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_WORKFLOW = "workflow";
  @SerializedName(SERIALIZED_NAME_WORKFLOW)
  private V1beta1ApplicationStatusWorkflow workflow;


  public V1beta1ApplicationStatus appliedResources(List<V1beta1ApplicationStatusAppliedResources> appliedResources) {
    
    this.appliedResources = appliedResources;
    return this;
  }

  public V1beta1ApplicationStatus addAppliedResourcesItem(V1beta1ApplicationStatusAppliedResources appliedResourcesItem) {
    if (this.appliedResources == null) {
      this.appliedResources = new ArrayList<>();
    }
    this.appliedResources.add(appliedResourcesItem);
    return this;
  }

   /**
   * AppliedResources record the resources that the  workflow step apply.
   * @return appliedResources
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AppliedResources record the resources that the  workflow step apply.")

  public List<V1beta1ApplicationStatusAppliedResources> getAppliedResources() {
    return appliedResources;
  }


  public void setAppliedResources(List<V1beta1ApplicationStatusAppliedResources> appliedResources) {
    this.appliedResources = appliedResources;
  }


  public V1beta1ApplicationStatus components(List<V1beta1ApplicationStatusComponents> components) {
    
    this.components = components;
    return this;
  }

  public V1beta1ApplicationStatus addComponentsItem(V1beta1ApplicationStatusComponents componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

   /**
   * Components record the related Components created by Application Controller
   * @return components
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Components record the related Components created by Application Controller")

  public List<V1beta1ApplicationStatusComponents> getComponents() {
    return components;
  }


  public void setComponents(List<V1beta1ApplicationStatusComponents> components) {
    this.components = components;
  }


  public V1beta1ApplicationStatus conditions(List<V1beta1WorkflowStepDefinitionStatusConditions> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public V1beta1ApplicationStatus addConditionsItem(V1beta1WorkflowStepDefinitionStatusConditions conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * Conditions of the resource.
   * @return conditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Conditions of the resource.")

  public List<V1beta1WorkflowStepDefinitionStatusConditions> getConditions() {
    return conditions;
  }


  public void setConditions(List<V1beta1WorkflowStepDefinitionStatusConditions> conditions) {
    this.conditions = conditions;
  }


  public V1beta1ApplicationStatus latestRevision(V1beta1ApplicationStatusLatestRevision latestRevision) {
    
    this.latestRevision = latestRevision;
    return this;
  }

   /**
   * Get latestRevision
   * @return latestRevision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationStatusLatestRevision getLatestRevision() {
    return latestRevision;
  }


  public void setLatestRevision(V1beta1ApplicationStatusLatestRevision latestRevision) {
    this.latestRevision = latestRevision;
  }


  public V1beta1ApplicationStatus observedGeneration(Long observedGeneration) {
    
    this.observedGeneration = observedGeneration;
    return this;
  }

   /**
   * The generation observed by the application controller.
   * @return observedGeneration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The generation observed by the application controller.")

  public Long getObservedGeneration() {
    return observedGeneration;
  }


  public void setObservedGeneration(Long observedGeneration) {
    this.observedGeneration = observedGeneration;
  }


  public V1beta1ApplicationStatus policy(List<V1beta1ApplicationStatusPolicy> policy) {
    
    this.policy = policy;
    return this;
  }

  public V1beta1ApplicationStatus addPolicyItem(V1beta1ApplicationStatusPolicy policyItem) {
    if (this.policy == null) {
      this.policy = new ArrayList<>();
    }
    this.policy.add(policyItem);
    return this;
  }

   /**
   * PolicyStatus records the status of policy Deprecated This field is only used by EnvBinding Policy which is deprecated.
   * @return policy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PolicyStatus records the status of policy Deprecated This field is only used by EnvBinding Policy which is deprecated.")

  public List<V1beta1ApplicationStatusPolicy> getPolicy() {
    return policy;
  }


  public void setPolicy(List<V1beta1ApplicationStatusPolicy> policy) {
    this.policy = policy;
  }


  public V1beta1ApplicationStatus services(List<V1beta1ApplicationStatusServices> services) {
    
    this.services = services;
    return this;
  }

  public V1beta1ApplicationStatus addServicesItem(V1beta1ApplicationStatusServices servicesItem) {
    if (this.services == null) {
      this.services = new ArrayList<>();
    }
    this.services.add(servicesItem);
    return this;
  }

   /**
   * Services record the status of the application services
   * @return services
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Services record the status of the application services")

  public List<V1beta1ApplicationStatusServices> getServices() {
    return services;
  }


  public void setServices(List<V1beta1ApplicationStatusServices> services) {
    this.services = services;
  }


  public V1beta1ApplicationStatus status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * ApplicationPhase is a label for the condition of an application at the current time
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ApplicationPhase is a label for the condition of an application at the current time")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public V1beta1ApplicationStatus workflow(V1beta1ApplicationStatusWorkflow workflow) {
    
    this.workflow = workflow;
    return this;
  }

   /**
   * Get workflow
   * @return workflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1ApplicationStatusWorkflow getWorkflow() {
    return workflow;
  }


  public void setWorkflow(V1beta1ApplicationStatusWorkflow workflow) {
    this.workflow = workflow;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationStatus v1beta1ApplicationStatus = (V1beta1ApplicationStatus) o;
    return Objects.equals(this.appliedResources, v1beta1ApplicationStatus.appliedResources) &&
        Objects.equals(this.components, v1beta1ApplicationStatus.components) &&
        Objects.equals(this.conditions, v1beta1ApplicationStatus.conditions) &&
        Objects.equals(this.latestRevision, v1beta1ApplicationStatus.latestRevision) &&
        Objects.equals(this.observedGeneration, v1beta1ApplicationStatus.observedGeneration) &&
        Objects.equals(this.policy, v1beta1ApplicationStatus.policy) &&
        Objects.equals(this.services, v1beta1ApplicationStatus.services) &&
        Objects.equals(this.status, v1beta1ApplicationStatus.status) &&
        Objects.equals(this.workflow, v1beta1ApplicationStatus.workflow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appliedResources, components, conditions, latestRevision, observedGeneration, policy, services, status, workflow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationStatus {\n");
    sb.append("    appliedResources: ").append(toIndentedString(appliedResources)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    latestRevision: ").append(toIndentedString(latestRevision)).append("\n");
    sb.append("    observedGeneration: ").append(toIndentedString(observedGeneration)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    workflow: ").append(toIndentedString(workflow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

