/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.oam.core.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WorkflowExecuteMode defines the mode of workflow execution
 */
@ApiModel(description = "WorkflowExecuteMode defines the mode of workflow execution")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-19T04:50:27.278Z[Etc/UTC]")
public class V1beta1ApplicationSpecWorkflowMode {
  public static final String SERIALIZED_NAME_STEPS = "steps";
  @SerializedName(SERIALIZED_NAME_STEPS)
  private String steps;

  public static final String SERIALIZED_NAME_SUB_STEPS = "subSteps";
  @SerializedName(SERIALIZED_NAME_SUB_STEPS)
  private String subSteps;


  public V1beta1ApplicationSpecWorkflowMode steps(String steps) {
    
    this.steps = steps;
    return this;
  }

   /**
   * Steps is the mode of workflow steps execution
   * @return steps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Steps is the mode of workflow steps execution")

  public String getSteps() {
    return steps;
  }


  public void setSteps(String steps) {
    this.steps = steps;
  }


  public V1beta1ApplicationSpecWorkflowMode subSteps(String subSteps) {
    
    this.subSteps = subSteps;
    return this;
  }

   /**
   * SubSteps is the mode of workflow sub steps execution
   * @return subSteps
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "SubSteps is the mode of workflow sub steps execution")

  public String getSubSteps() {
    return subSteps;
  }


  public void setSubSteps(String subSteps) {
    this.subSteps = subSteps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1ApplicationSpecWorkflowMode v1beta1ApplicationSpecWorkflowMode = (V1beta1ApplicationSpecWorkflowMode) o;
    return Objects.equals(this.steps, v1beta1ApplicationSpecWorkflowMode.steps) &&
        Objects.equals(this.subSteps, v1beta1ApplicationSpecWorkflowMode.subSteps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(steps, subSteps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1ApplicationSpecWorkflowMode {\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    subSteps: ").append(toIndentedString(subSteps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

